# fly.toml file generated for roll-for-point-buy on 2022-08-27T15:06:34+02:00

app = "roll-for-point-buy"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
